default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: airplane-price-monitor_development

test:
  <<: *default
  database: airplane-price-monitor_test

production:
  <<: *default
  database: airplane-price-monitor_production
